name: Self test

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - id: self-test
        uses: ./
        with:
          service: self-test
          tags: '["git-sha-${{ github.sha }}", "do-not-use-me"]'
          docker-compose-file: custom-docker-path/docker-compose.yml
          dry-run: true
      - run: |
          echo ${{ steps.self-test.outputs.published }}
