name: Self Test

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Invoke action
        id: self-test
        uses: ./
        with:
          service: self-test
          tags: '["git-sha-${{ github.sha }}", "do-not-use-me"]'
          docker-compose-file: custom-docker-path/docker-compose.yml
          dry-run: true
      - name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.self-test.outputs) }}
        run: |
          echo "${OUTPUTS}"
